apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: achoistic98/blog_database:latest
          ports:
            - containerPort: 3306
          # volumeMounts:
          #   - name: database-volume
          #     mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "blogdb"
            - name: TZ
              value: Asia/Seoul
      # volumes:
      #   - name: database-volume
      #     hostPath:
      #       path: /volumes