apiVersion: v1
kind: Service
metadata:
  name: mysql-ha
spec:
  selector:
    # statefulset.kubernetes.io/pod-name: mysql-ha-0
    app: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql-ha-1
# spec:
#   selector:
#     statefulset.kubernetes.io/pod-name: mysql-ha-1
#   ports:
#     - protocol: TCP
#       port: 3306
#       targetPort: 3306
#   type: ClusterIP
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql-ha-2
# spec:
#   selector:
#     statefulset.kubernetes.io/pod-name: mysql-ha-2
#   ports:
#     - protocol: TCP
#       port: 3306
#       targetPort: 3306
#   type: ClusterIP