apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-ha
spec:
  serviceName: mysql-ha
  replicas: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      initContainers:
        - name: init-mysql
          image: achoistic98/blog_mysqls:latest
          command:
          - bash
          - "-c"
          - |
            set -ex
            [[ $HOSTNAME =~ -([0-9]+)$ ]] || exit 1
            ordinal=${BASH_REMATCH[1]}
            if [[ $ordinal -eq 0 ]]; then
              cp /cfg/mysql-master.cnf /mnt/
              cp /cfg/init-master.sql /mnt/
            else
              cp /cfg/mysql-slave.cnf /mnt/
              cp /cfg/init-slave.sql /mnt/
            fi
          volumeMounts:
          - name: local-vol
            mountPath: /mnt/
      containers:
        - name: database
          image: mysql:latest
          ports:
            - containerPort: 3306
          volumeMounts:
          - name: local-vol
            mountPath: /etc/mysql/conf.d/
          - name: local-vol
            mountPath: /docker-entrypoint-initdb.d/
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "blogdb"
            - name: MYSQL_USER
              value: "slave"
            - name: MYSQL_PASSWORD
              value: "password"
      volumes:
        - name: database-volume
          hostPath:
            path: /volumes
  volumeClaimTemplates:
  - metadata:
      name: local-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 1Gi