apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-ha
spec:
  serviceName: mysql-ha
  replicas: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      initContainers:
        - name: init-mysql
          image: achoistic98/blog_mysqls:latest
          command:
          - bash
          - "-c"
          - |
            set -ex
            [[ $HOSTNAME =~ -([0-9]+)$ ]] || exit 1
            ordinal=${BASH_REMATCH[1]}
            if [[ $ordinal -eq 0 ]]; then
              cp /cfg/mysql-master.cnf /mnt/cfg/mysql-master.cnf
              cp /cfg/init-master.sql /mnt/init/init-master.sql
            else
              cp /cfg/mysql-slave.cnf /mnt/cfg/mysql-slave.cnf
              cp /cfg/init-slave.sql /mnt/init/init-slave.sql
            fi
          volumeMounts:
            - name: master-slave-cfg
              mountPath: /mnt/cfg/
            - name: master-slave-init
              mountPath: /mnt/init/
      containers:
        - name: database
          image: mysql:latest
          ports:
            - containerPort: 3306
          volumeMounts:
          - name: master-slave-cfg
            mountPath: /etc/mysql/conf.d
          - name: master-slave-init
            mountPath: /docker-entrypoint-initdb.d
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "blogdb"
            - name: MYSQL_USER
              value: "slave"
            - name: MYSQL_PASSWORD
              value: "password"
      volumes:
        - name: database-volume
          hostPath:
            path: /volumes
        - name: master-slave-cfg
          hostPath:
            path: /volumes/cfg
        - name: master-slave-init
          hostPath:
            path: /volumes/init