apiVersion: v1
kind: Service
metadata:
  name: mysql-ha-0
spec:
  selector:
    app: database
    ha: one
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-ha-1
spec:
  selector:
    app: database
    ha: two
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-ha-2
spec:
  selector:
    app: database
    ha: three
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP