apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: achoistic98/blog_frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: frontend
              topologyKey: "kubernetes.io/hostname"
      env:
        - name: REACT_APP_HOST
          value: "http://localhost"
        # - name: REACT_APP_HOST # prod
        #   value: "https://www.choigonyok.com" # prod