apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-ha-haproxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - haproxy
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: haproxy
        image: achoistic98/blog_haproxy_mysql:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        - containerPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-ha-haproxy
  namespace: devops-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: haproxy-jenkins
  template:
    metadata:
      labels:
        app: haproxy-jenkins
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - haproxy-jenkins
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: haproxy-jenkins
        image: achoistic98/blog_haproxy_jenkins:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        - containerPort: 8080