apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: devops-system
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc