apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: controller
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30010
  type: NodePort
